spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB
  cloud:
    azure:
      resource-group: browndwarf
      region: Korea Central
      storage:
        account: browndwarfstorage
server:
  port: 9001